### ISSUE TITLE
FLAC Support

### ISSUE THREAD

**Issue by flawiddsouza** [agrahn/ABLoopPlayer#1]
Hey, will you add FLAC support to this?

**Comment by agrahn** [comment]
The player is built around the `<video>` and `<audio>` tags of HTML5. Thus, the formats that can be played back depend on how these tags are implemented in the current web browsers. I did not care much about formats as most of the popular ones are supported by FF and Chrome. I don't think I will put much effort into the support of other formats.

While searching the web, I learned that FF and Chrome purportedly support FLAC already. See, e. g. https://news.ycombinator.com/item?id=12422891 or http://www.ghacks.net/2016/08/30/firefox-51-flac-audio-codec-support/

**Comment by flawiddsouza** [comment]
FLAC doesn't work on either Chrome or Firefox. I have the latest versions. Guess there's nothing that can be done about that.

**Comment by agrahn** [comment]
Yes, it looks like that. Thank you for starring the project.

**Comment by flawiddsouza** [comment]
Maybe this could be useful if you ever think of adding flac support:
https://github.com/audiocogs/flac.js
https://github.com/audiocogs/aurora.js/wiki/Getting-Started

**Comment by agrahn** [comment]
Flac seems to be supported in major web browsers nowadays. I downloaded and tested some samples from https://filesamples.com/formats/flac .
